//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazinsAtenea.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrazinsAtenea {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrazinsAtenea() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrazinsAtenea.GlobalResources.TrazinsAtenea", typeof(TrazinsAtenea).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Montaje | Empaquetado.
        /// </summary>
        internal static string AssemblyPackaging {
            get {
                return ResourceManager.GetString("AssemblyPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones específicas de montaje o empaquetado.
        /// </summary>
        internal static string AssemblyPackagingRemarks {
            get {
                return ResourceManager.GetString("AssemblyPackagingRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloque.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caducidad.
        /// </summary>
        internal static string Caducity {
            get {
                return ResourceManager.GetString("Caducity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturar.
        /// </summary>
        internal static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar de usuario.
        /// </summary>
        internal static string ChangeUser {
            get {
                return ResourceManager.GetString("ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Caja/Id.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Coste.
        /// </summary>
        internal static string CostCenter {
            get {
                return ResourceManager.GetString("CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Datos y procesos.
        /// </summary>
        internal static string DataProcesses {
            get {
                return ResourceManager.GetString("DataProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Ubicación predeterminada.
        /// </summary>
        internal static string DefaultUbication {
            get {
                return ResourceManager.GetString("DefaultUbication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro?.
        /// </summary>
        internal static string DeleteMessageTitle {
            get {
                return ResourceManager.GetString("DeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externo.
        /// </summary>
        internal static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imágenes.
        /// </summary>
        internal static string FilterImageType {
            get {
                return ResourceManager.GetString("FilterImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (*.jpeg, *.jpg, *.png, *.gif)|*.jpeg;*.jpg;*.png;*.gif.
        /// </summary>
        internal static string FilterImageTypes {
            get {
                return ResourceManager.GetString("FilterImageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |Archivos vídeo.
        /// </summary>
        internal static string FilterVideoType {
            get {
                return ResourceManager.GetString("FilterVideoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.avi, *.mp4, *.mpeg, *.mpg, *.wmv) | *.avi; *.mp4; *.mpeg; *.mpg; *.wmv.
        /// </summary>
        internal static string FilterVideoTypes {
            get {
                return ResourceManager.GetString("FilterVideoTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Generales.
        /// </summary>
        internal static string GeneralData {
            get {
                return ResourceManager.GetString("GeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genérico.
        /// </summary>
        internal static string Generic {
            get {
                return ResourceManager.GetString("Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción de grupo.
        /// </summary>
        internal static string GroupDescription {
            get {
                return ResourceManager.GetString("GroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de grupo.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Grupo.
        /// </summary>
        internal static string GroupNew {
            get {
                return ResourceManager.GetString("GroupNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones de grupo.
        /// </summary>
        internal static string GroupObservations {
            get {
                return ResourceManager.GetString("GroupObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de Grupos.
        /// </summary>
        internal static string GroupTitle {
            get {
                return ResourceManager.GetString("GroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Histórico.
        /// </summary>
        internal static string Historical {
            get {
                return ResourceManager.GetString("Historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Imágenes y vídeos.
        /// </summary>
        internal static string ImageVideo {
            get {
                return ResourceManager.GetString("ImageVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suelto.
        /// </summary>
        internal static string Instrumental {
            get {
                return ResourceManager.GetString("Instrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir instrumental.
        /// </summary>
        internal static string InstrumentalAdd {
            get {
                return ResourceManager.GetString("InstrumentalAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Instrumental.
        /// </summary>
        internal static string InstrumentalSet {
            get {
                return ResourceManager.GetString("InstrumentalSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventario.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localización.
        /// </summary>
        internal static string Locate {
            get {
                return ResourceManager.GetString("Locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclos hasta mantenimiento preventivo.
        /// </summary>
        internal static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Instrumental.
        /// </summary>
        internal static string ModifyInstrumental {
            get {
                return ResourceManager.GetString("ModifyInstrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar caja.
        /// </summary>
        internal static string ModifySet {
            get {
                return ResourceManager.GetString("ModifySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Caja.
        /// </summary>
        internal static string NewSetTitle {
            get {
                return ResourceManager.GetString("NewSetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir archivo.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embalaje.
        /// </summary>
        internal static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesos.
        /// </summary>
        internal static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y continuar.
        /// </summary>
        internal static string SaveContinue {
            get {
                return ResourceManager.GetString("SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y salir.
        /// </summary>
        internal static string SaveExit {
            get {
                return ResourceManager.GetString("SaveExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona una ubicación donde se almacenará esta caja de forma predeterminada.
        /// </summary>
        internal static string SelectDefaultUbication {
            get {
                return ResourceManager.GetString("SelectDefaultUbication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona desde 1 hasta 3 métodos de esterilización.
        /// </summary>
        internal static string SelectSterilizationMethods {
            get {
                return ResourceManager.GetString("SelectSterilizationMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona desde 1 hasta 3 métodos de lavados.
        /// </summary>
        internal static string SelectWashesMethods {
            get {
                return ResourceManager.GetString("SelectWashesMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estante.
        /// </summary>
        internal static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caja.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de caja.
        /// </summary>
        internal static string SetCode {
            get {
                return ResourceManager.GetString("SetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre caja.
        /// </summary>
        internal static string SetName {
            get {
                return ResourceManager.GetString("SetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caja de Muestra.
        /// </summary>
        internal static string SetSample {
            get {
                return ResourceManager.GetString("SetSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca esta opción si esta caja se usa como plantilla para preparar nuevas cajas.
        /// </summary>
        internal static string SetSampleInfo {
            get {
                return ResourceManager.GetString("SetSampleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de caja.
        /// </summary>
        internal static string SetType {
            get {
                return ResourceManager.GetString("SetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Lavados.
        /// </summary>
        internal static string SetWashes {
            get {
                return ResourceManager.GetString("SetWashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidad.
        /// </summary>
        internal static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situación Especial.
        /// </summary>
        internal static string SpecialSituation {
            get {
                return ResourceManager.GetString("SpecialSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Ciclos/Esterilización.
        /// </summary>
        internal static string Sterilization {
            get {
                return ResourceManager.GetString("Sterilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones específicas de esterilización.
        /// </summary>
        internal static string SteriRemarks {
            get {
                return ResourceManager.GetString("SteriRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        internal static string Ubication {
            get {
                return ResourceManager.GetString("Ubication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavados.
        /// </summary>
        internal static string Washes {
            get {
                return ResourceManager.GetString("Washes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones específicas de lavado.
        /// </summary>
        internal static string WashingRemarks {
            get {
                return ResourceManager.GetString("WashingRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí, enviar a la papelera.
        /// </summary>
        internal static string YesSend {
            get {
                return ResourceManager.GetString("YesSend", resourceCulture);
            }
        }
    }
}
