//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazinsAtenea.ServiceWSTrazinsAtenea {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://WSTrazinsAtenea.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuditMaquinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuditProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuditUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HosIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuditMaquina {
            get {
                return this.AuditMaquinaField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditMaquinaField, value) != true)) {
                    this.AuditMaquinaField = value;
                    this.RaisePropertyChanged("AuditMaquina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuditProceso {
            get {
                return this.AuditProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditProcesoField, value) != true)) {
                    this.AuditProcesoField = value;
                    this.RaisePropertyChanged("AuditProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuditUsuario {
            get {
                return this.AuditUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditUsuarioField, value) != true)) {
                    this.AuditUsuarioField = value;
                    this.RaisePropertyChanged("AuditUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChId {
            get {
                return this.ChIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ChIdField, value) != true)) {
                    this.ChIdField = value;
                    this.RaisePropertyChanged("ChId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HosId {
            get {
                return this.HosIdField;
            }
            set {
                if ((object.ReferenceEquals(this.HosIdField, value) != true)) {
                    this.HosIdField = value;
                    this.RaisePropertyChanged("HosId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Especialidad", Namespace="http://WSTrazinsAtenea.com")]
    [System.SerializableAttribute()]
    public partial class Especialidad : TrazinsAtenea.ServiceWSTrazinsAtenea.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EspIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EspId {
            get {
                return this.EspIdField;
            }
            set {
                if ((this.EspIdField.Equals(value) != true)) {
                    this.EspIdField = value;
                    this.RaisePropertyChanged("EspId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Embalaje", Namespace="http://WSTrazinsAtenea.com")]
    [System.SerializableAttribute()]
    public partial class Embalaje : TrazinsAtenea.ServiceWSTrazinsAtenea.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CaducidadDiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CaducidadMesesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ConIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CaducidadDias {
            get {
                return this.CaducidadDiasField;
            }
            set {
                if ((this.CaducidadDiasField.Equals(value) != true)) {
                    this.CaducidadDiasField = value;
                    this.RaisePropertyChanged("CaducidadDias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CaducidadMeses {
            get {
                return this.CaducidadMesesField;
            }
            set {
                if ((this.CaducidadMesesField.Equals(value) != true)) {
                    this.CaducidadMesesField = value;
                    this.RaisePropertyChanged("CaducidadMeses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ConId {
            get {
                return this.ConIdField;
            }
            set {
                if ((this.ConIdField.Equals(value) != true)) {
                    this.ConIdField = value;
                    this.RaisePropertyChanged("ConId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Caja", Namespace="http://WSTrazinsAtenea.com")]
    [System.SerializableAttribute()]
    public partial class Caja : TrazinsAtenea.ServiceWSTrazinsAtenea.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CHIdPropietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CajaId_CodigoCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EspIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Especialidad_DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HosIdPropietarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activa {
            get {
                return this.ActivaField;
            }
            set {
                if ((this.ActivaField.Equals(value) != true)) {
                    this.ActivaField = value;
                    this.RaisePropertyChanged("Activa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CHIdPropietario {
            get {
                return this.CHIdPropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CHIdPropietarioField, value) != true)) {
                    this.CHIdPropietarioField = value;
                    this.RaisePropertyChanged("CHIdPropietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaId {
            get {
                return this.CajaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaIdField, value) != true)) {
                    this.CajaIdField = value;
                    this.RaisePropertyChanged("CajaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CajaId_CodigoCaja {
            get {
                return this.CajaId_CodigoCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.CajaId_CodigoCajaField, value) != true)) {
                    this.CajaId_CodigoCajaField = value;
                    this.RaisePropertyChanged("CajaId_CodigoCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCaja {
            get {
                return this.CodigoCajaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCajaField, value) != true)) {
                    this.CodigoCajaField = value;
                    this.RaisePropertyChanged("CodigoCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EspId {
            get {
                return this.EspIdField;
            }
            set {
                if ((this.EspIdField.Equals(value) != true)) {
                    this.EspIdField = value;
                    this.RaisePropertyChanged("EspId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especialidad_Descripcion {
            get {
                return this.Especialidad_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.Especialidad_DescripcionField, value) != true)) {
                    this.Especialidad_DescripcionField = value;
                    this.RaisePropertyChanged("Especialidad_Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HosIdPropietario {
            get {
                return this.HosIdPropietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HosIdPropietarioField, value) != true)) {
                    this.HosIdPropietarioField = value;
                    this.RaisePropertyChanged("HosIdPropietario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://WSTrazinsAtenea.com")]
    [System.SerializableAttribute()]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idioma {
            get {
                return this.IdiomaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdiomaField, value) != true)) {
                    this.IdiomaField = value;
                    this.RaisePropertyChanged("Idioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WSTrazinsAtenea.com", ConfigurationName="ServiceWSTrazinsAtenea.IWSTrazinsAtenea")]
    public interface IWSTrazinsAtenea {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_Select_List", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_Select_ListResponse")]
        TrazinsAtenea.ServiceWSTrazinsAtenea.Caja[] Caja_Select_List(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_Select_List", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_Select_ListResponse")]
        System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Caja[]> Caja_Select_ListAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_Select", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_SelectResponse")]
        TrazinsAtenea.ServiceWSTrazinsAtenea.Caja Caja_Select(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_Select", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_SelectResponse")]
        System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Caja> Caja_SelectAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_Insert", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_InsertResponse")]
        string Caja_Insert(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_Insert", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_InsertResponse")]
        System.Threading.Tasks.Task<string> Caja_InsertAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_Update", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_UpdateResponse")]
        string Caja_Update(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_Update", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Caja_UpdateResponse")]
        System.Threading.Tasks.Task<string> Caja_UpdateAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_Select_List", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_Select_ListResponse")]
        TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad[] Especialidad_Select_List(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_Select_List", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_Select_ListResponse")]
        System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad[]> Especialidad_Select_ListAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_Select", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_SelectResponse")]
        TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad Especialidad_Select(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_Select", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_SelectResponse")]
        System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad> Especialidad_SelectAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_Insert", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_InsertResponse")]
        string Especialidad_Insert(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_Insert", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_InsertResponse")]
        System.Threading.Tasks.Task<string> Especialidad_InsertAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_Update", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_UpdateResponse")]
        string Especialidad_Update(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_Update", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Especialidad_UpdateResponse")]
        System.Threading.Tasks.Task<string> Especialidad_UpdateAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_Select_List", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_Select_ListResponse")]
        TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje[] Embalaje_Select_List(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_Select_List", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_Select_ListResponse")]
        System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje[]> Embalaje_Select_ListAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_Select", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_SelectResponse")]
        TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje Embalaje_Select(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_Select", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_SelectResponse")]
        System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje> Embalaje_SelectAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_Insert", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_InsertResponse")]
        string Embalaje_Insert(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_Insert", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_InsertResponse")]
        System.Threading.Tasks.Task<string> Embalaje_InsertAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_Update", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_UpdateResponse")]
        string Embalaje_Update(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_Update", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Embalaje_UpdateResponse")]
        System.Threading.Tasks.Task<string> Embalaje_UpdateAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Mensaje_Select", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Mensaje_SelectResponse")]
        TrazinsAtenea.ServiceWSTrazinsAtenea.Mensaje Mensaje_Select(TrazinsAtenea.ServiceWSTrazinsAtenea.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Mensaje_Select", ReplyAction="http://WSTrazinsAtenea.com/IWSTrazinsAtenea/Mensaje_SelectResponse")]
        System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Mensaje> Mensaje_SelectAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Mensaje mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSTrazinsAteneaChannel : TrazinsAtenea.ServiceWSTrazinsAtenea.IWSTrazinsAtenea, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTrazinsAteneaClient : System.ServiceModel.ClientBase<TrazinsAtenea.ServiceWSTrazinsAtenea.IWSTrazinsAtenea>, TrazinsAtenea.ServiceWSTrazinsAtenea.IWSTrazinsAtenea {
        
        public WSTrazinsAteneaClient() {
        }
        
        public WSTrazinsAteneaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTrazinsAteneaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTrazinsAteneaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTrazinsAteneaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrazinsAtenea.ServiceWSTrazinsAtenea.Caja[] Caja_Select_List(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja) {
            return base.Channel.Caja_Select_List(caja);
        }
        
        public System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Caja[]> Caja_Select_ListAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja) {
            return base.Channel.Caja_Select_ListAsync(caja);
        }
        
        public TrazinsAtenea.ServiceWSTrazinsAtenea.Caja Caja_Select(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja) {
            return base.Channel.Caja_Select(caja);
        }
        
        public System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Caja> Caja_SelectAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja) {
            return base.Channel.Caja_SelectAsync(caja);
        }
        
        public string Caja_Insert(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja) {
            return base.Channel.Caja_Insert(caja);
        }
        
        public System.Threading.Tasks.Task<string> Caja_InsertAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja) {
            return base.Channel.Caja_InsertAsync(caja);
        }
        
        public string Caja_Update(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja) {
            return base.Channel.Caja_Update(caja);
        }
        
        public System.Threading.Tasks.Task<string> Caja_UpdateAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Caja caja) {
            return base.Channel.Caja_UpdateAsync(caja);
        }
        
        public TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad[] Especialidad_Select_List(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad) {
            return base.Channel.Especialidad_Select_List(especialidad);
        }
        
        public System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad[]> Especialidad_Select_ListAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad) {
            return base.Channel.Especialidad_Select_ListAsync(especialidad);
        }
        
        public TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad Especialidad_Select(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad) {
            return base.Channel.Especialidad_Select(especialidad);
        }
        
        public System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad> Especialidad_SelectAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad) {
            return base.Channel.Especialidad_SelectAsync(especialidad);
        }
        
        public string Especialidad_Insert(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad) {
            return base.Channel.Especialidad_Insert(especialidad);
        }
        
        public System.Threading.Tasks.Task<string> Especialidad_InsertAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad) {
            return base.Channel.Especialidad_InsertAsync(especialidad);
        }
        
        public string Especialidad_Update(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad) {
            return base.Channel.Especialidad_Update(especialidad);
        }
        
        public System.Threading.Tasks.Task<string> Especialidad_UpdateAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Especialidad especialidad) {
            return base.Channel.Especialidad_UpdateAsync(especialidad);
        }
        
        public TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje[] Embalaje_Select_List(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje) {
            return base.Channel.Embalaje_Select_List(embalaje);
        }
        
        public System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje[]> Embalaje_Select_ListAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje) {
            return base.Channel.Embalaje_Select_ListAsync(embalaje);
        }
        
        public TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje Embalaje_Select(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje) {
            return base.Channel.Embalaje_Select(embalaje);
        }
        
        public System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje> Embalaje_SelectAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje) {
            return base.Channel.Embalaje_SelectAsync(embalaje);
        }
        
        public string Embalaje_Insert(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje) {
            return base.Channel.Embalaje_Insert(embalaje);
        }
        
        public System.Threading.Tasks.Task<string> Embalaje_InsertAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje) {
            return base.Channel.Embalaje_InsertAsync(embalaje);
        }
        
        public string Embalaje_Update(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje) {
            return base.Channel.Embalaje_Update(embalaje);
        }
        
        public System.Threading.Tasks.Task<string> Embalaje_UpdateAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Embalaje embalaje) {
            return base.Channel.Embalaje_UpdateAsync(embalaje);
        }
        
        public TrazinsAtenea.ServiceWSTrazinsAtenea.Mensaje Mensaje_Select(TrazinsAtenea.ServiceWSTrazinsAtenea.Mensaje mensaje) {
            return base.Channel.Mensaje_Select(mensaje);
        }
        
        public System.Threading.Tasks.Task<TrazinsAtenea.ServiceWSTrazinsAtenea.Mensaje> Mensaje_SelectAsync(TrazinsAtenea.ServiceWSTrazinsAtenea.Mensaje mensaje) {
            return base.Channel.Mensaje_SelectAsync(mensaje);
        }
    }
}
